version: "3.8"
services:  
  db:
    image: "postgres:14-bullseye"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apidb
    restart: always
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/opt/microservice/app/
    restart: always